
INCLUDEPATH += $$PWD

HEADERS += \
    $$PWD/r_rtu/r_rturegenum.h \
    $$PWD/r_rtu/r_rtusent.h \
    $$PWD/r_rtu/r_rturecv.h \
    $$PWD/r_rtu/r_rtutrans.h \
    $$PWD/r_com/r_configfile.h \
    $$PWD/r_com/r_datapackets.h \
    $$PWD/r_sql/r_dbalarm.h \
    $$PWD/r_sql/r_dbenv.h \
    $$PWD/r_sql/r_dblinerecords.h \
    $$PWD/r_sql/r_dblinethresholds.h \
    $$PWD/r_sql/r_dbmodbuscmd.h \
    $$PWD/r_sql/r_dbmodbustrans.h \
    $$PWD/r_sql/r_dboutputrecords.h \
    $$PWD/r_sql/r_dblooprecords.h \
    $$PWD/r_dp/r_dpalarmsave.h \
    $$PWD/r_dp/r_dpsaveenv.h \
    $$PWD/r_dp/r_dpsavelinerecord.h \
    $$PWD/r_dp/r_dpsavelinethreshold.h \
    $$PWD/r_dp/r_dpsaveoutput.h \
    $$PWD/r_dp/r_dpsaveloop.h \
    $$PWD/r_dp/r_dpsavetrans.h \
    $$PWD/r_dp/r_dpthread.h \
    $$PWD/r_logs/r_logalarmwid.h \
    $$PWD/r_logs/r_logenvwid.h \
    $$PWD/r_logs/r_loglinerecordwid.h \
    $$PWD/r_logs/r_loglinethresholdwid.h \
    $$PWD/r_logs/r_logmodbuscmdwid.h \
    $$PWD/r_logs/r_logmodbustranswid.h \
    $$PWD/r_logs/r_logoutputrecordwid.h \
    $$PWD/r_logs/r_loglooprecordwid.h \
    $$PWD/r_logs/r_logswid.h \
    $$PWD/r_service/json/r_buildjson.h \
    $$PWD/r_service/r_servicethread.h \
    $$PWD/r_toolbox/r_settingtoolwid.h \
    $$PWD/r_toolbox/r_logstoolwid.h \
    $$PWD/r_toolbox/r_toolboxwid.h \
    $$PWD/rpdu_mainwid.h \
    $$PWD/r_setting/rset_mainwid.h \
    $$PWD/r_snmp/r_snmpsend.h \
    $$PWD/r_snmp/r_snmptrans.h \
    $$PWD/r_snmp/r_snmprecv.h \
    $$PWD/r_toolbox/r_statustoolwid.h \
    $$PWD/r_toolbox/r_modetoolwid.h \
    $$PWD/r_rtu/r_rtuthread.h \
    $$PWD/r_status/r_statuswid.h \
    $$PWD/r_setting/r_setsnmp/rset_snmpthread.h \
    $$PWD/r_setting/r_setrtu/rset_rtuthread.h \
    $$PWD/r_setting/r_setele/rset_eleitemwid.h \
    $$PWD/r_setting/r_setele/rset_outputelewid.h \
    $$PWD/r_setting/r_setenv/rset_envitemwid.h \
    $$PWD/r_setting/r_setenv/rset_envunitwid.h \
    $$PWD/r_setting/r_setenv/rset_envwid.h \
    $$PWD/r_setting/r_setline/rset_lineitemwid.h \
    $$PWD/r_setting/r_setline/rset_lineunitwid.h \
    $$PWD/r_setting/r_setline/rset_linewid.h \
    $$PWD/r_setting/r_setloop/rset_loopitemwid.h \
    $$PWD/r_setting/r_setloop/rset_loopunitwid.h \
    $$PWD/r_setting/r_setloop/rset_loopwid.h \
    $$PWD/r_setting/r_setsw/rset_switemwid.h \
    $$PWD/r_setting/r_setsw/rset_swwid.h \
    $$PWD/r_setting/r_setthreshold/rset_thresholditemwid.h \
    $$PWD/r_setting/r_setthreshold/rset_thresholdoutputwid.h \
    $$PWD/r_setting/r_setswcycle/rset_swcycleitemwid.h \
    $$PWD/r_setting/r_setswcycle/rset_swcyclewid.h \
    $$PWD/r_test/rtest_mainwid.h \
    $$PWD/r_test/rtest_transthread.h \
    $$PWD/r_test/rtest_config.h \
    $$PWD/r_test/rtest_corethread.h


	
SOURCES += \
    $$PWD/r_rtu/r_rtusent.cpp \
    $$PWD/r_rtu/r_rturecv.cpp \
    $$PWD/r_rtu/r_rtutrans.cpp \
    $$PWD/r_com/r_configfile.cpp \
    $$PWD/r_com/r_datapackets.cpp \
    $$PWD/r_sql/r_dbalarm.cpp \
    $$PWD/r_sql/r_dbenv.cpp \
    $$PWD/r_sql/r_dblinerecords.cpp \
    $$PWD/r_sql/r_dblinethresholds.cpp \
    $$PWD/r_sql/r_dbmodbuscmd.cpp \
    $$PWD/r_sql/r_dbmodbustrans.cpp \
    $$PWD/r_sql/r_dboutputrecords.cpp \
    $$PWD/r_sql/r_dblooprecords.cpp \
    $$PWD/r_dp/r_dpalarmsave.cpp \
    $$PWD/r_dp/r_dpsaveenv.cpp \
    $$PWD/r_dp/r_dpsavelinerecord.cpp \
    $$PWD/r_dp/r_dpsavelinethreshold.cpp \
    $$PWD/r_dp/r_dpsaveoutput.cpp \
    $$PWD/r_dp/r_dpsaveloop.cpp \
    $$PWD/r_dp/r_dpsavetrans.cpp \
    $$PWD/r_dp/r_dpthread.cpp \
    $$PWD/r_logs/r_logalarmwid.cpp \
    $$PWD/r_logs/r_logenvwid.cpp \
    $$PWD/r_logs/r_loglinerecordwid.cpp \
    $$PWD/r_logs/r_loglinethresholdwid.cpp \
    $$PWD/r_logs/r_logmodbuscmdwid.cpp \
    $$PWD/r_logs/r_logmodbustranswid.cpp \
    $$PWD/r_logs/r_logoutputrecordwid.cpp \
    $$PWD/r_logs/r_loglooprecordwid.cpp \
    $$PWD/r_logs/r_logswid.cpp \
    $$PWD/r_service/json/r_buildjson.cpp \
    $$PWD/r_service/r_servicethread.cpp \
    $$PWD/r_toolbox/r_settingtoolwid.cpp \
    $$PWD/r_toolbox/r_logstoolwid.cpp \
    $$PWD/r_toolbox/r_toolboxwid.cpp \
    $$PWD/rpdu_mainwid.cpp \
    $$PWD/r_setting/rset_mainwid.cpp \
    $$PWD/r_snmp/r_snmpsend.cpp \
    $$PWD/r_snmp/r_snmptrans.cpp \
    $$PWD/r_snmp/r_snmprecv.cpp \
    $$PWD/r_toolbox/r_statustoolwid.cpp \
    $$PWD/r_toolbox/r_modetoolwid.cpp \
    $$PWD/r_rtu/r_rtuthread.cpp \
    $$PWD/r_status/r_statuswid.cpp \
    $$PWD/r_setting/r_setsnmp/rset_snmpthread.cpp \
    $$PWD/r_setting/r_setrtu/rset_rtuthread.cpp \
    $$PWD/r_setting/r_setele/rset_eleitemwid.cpp \
    $$PWD/r_setting/r_setele/rset_outputelewid.cpp \
    $$PWD/r_setting/r_setenv/rset_envitemwid.cpp \
    $$PWD/r_setting/r_setenv/rset_envunitwid.cpp \
    $$PWD/r_setting/r_setenv/rset_envwid.cpp \
    $$PWD/r_setting/r_setline/rset_lineitemwid.cpp \
    $$PWD/r_setting/r_setline/rset_lineunitwid.cpp \
    $$PWD/r_setting/r_setline/rset_linewid.cpp \
    $$PWD/r_setting/r_setloop/rset_loopitemwid.cpp \
    $$PWD/r_setting/r_setloop/rset_loopunitwid.cpp \
    $$PWD/r_setting/r_setloop/rset_loopwid.cpp \
    $$PWD/r_setting/r_setsw/rset_switemwid.cpp \
    $$PWD/r_setting/r_setsw/rset_swwid.cpp \
    $$PWD/r_setting/r_setthreshold/rset_thresholditemwid.cpp \
    $$PWD/r_setting/r_setthreshold/rset_thresholdoutputwid.cpp \
    $$PWD/r_setting/r_setswcycle/rset_swcycleitemwid.cpp \
    $$PWD/r_setting/r_setswcycle/rset_swcyclewid.cpp \
    $$PWD/r_test/rtest_mainwid.cpp \
    $$PWD/r_test/rtest_transthread.cpp \
    $$PWD/r_test/rtest_config.cpp \
    $$PWD/r_test/rtest_corethread.cpp

FORMS += \
    $$PWD/r_logs/r_logswid.ui \
    $$PWD/rpdu_mainwid.ui \
    $$PWD/r_setting/rset_mainwid.ui \
    $$PWD/r_status/r_statuswid.ui \
    $$PWD/r_setting/r_setele/rset_eleitemwid.ui \
    $$PWD/r_setting/r_setele/rset_outputelewid.ui \
    $$PWD/r_setting/r_setenv/rset_envitemwid.ui \
    $$PWD/r_setting/r_setenv/rset_envunitwid.ui \
    $$PWD/r_setting/r_setenv/rset_envwid.ui \
    $$PWD/r_setting/r_setline/rset_lineitemwid.ui \
    $$PWD/r_setting/r_setline/rset_lineunitwid.ui \
    $$PWD/r_setting/r_setline/rset_linewid.ui \
    $$PWD/r_setting/r_setloop/rset_loopitemwid.ui \
    $$PWD/r_setting/r_setloop/rset_loopunitwid.ui \
    $$PWD/r_setting/r_setloop/rset_loopwid.ui \
    $$PWD/r_setting/r_setsw/rset_switemwid.ui \
    $$PWD/r_setting/r_setsw/rset_swwid.ui \
    $$PWD/r_setting/r_setthreshold/rset_thresholditemwid.ui \
    $$PWD/r_setting/r_setthreshold/rset_thresholdoutputwid.ui \
    $$PWD/r_setting/r_setswcycle/rset_swcycleitemwid.ui \
    $$PWD/r_setting/r_setswcycle/rset_swcyclewid.ui


